// @Description a Hook on the MainGameLoop case 4 routine (on pause)
// @HookAddress 0x4CC
// Mode: Thumb
// Made by ssp(shinespeciall)

// Changelog:
// v1.0 on 2022/02/22 by ssp
// create the patch

/** starts from 0x4CC, no alignment byte needed, jump to the end of the whole switch case
 * .thumb
    ldr r0, .DATA
    mov lr, r0
    ldr r0, .DATA + 4
    bx r0
 * .DATA:
    .word 0x08000631
    .word 0xAAAAAAAA
 * 
 * Hook String generated by gcc: 01488646 01480047 31060008 aaaaaaaa
 * @HookString 01488646 01480047 31060008 P
 */


#define ucBgmOff (*(volatile unsigned char*) 0x300001C)
#define ucTitle2f (*(volatile unsigned char*) 0x3000022)
#define ucGateNum (*(volatile unsigned char*) 0x3000025)
#define CurrentRoomHeader_MusicVolume (*(volatile unsigned short*) 0x300009E)
#define cPauseFlag (*(volatile unsigned short*) 0x3000C35)
#define GlobalGameMode (*(volatile unsigned short*) 0x3000C3A)
#define sGameSeq (*(volatile unsigned short*) 0x3000C3C)
#define BgmMapucSwSeq (*(volatile unsigned char*) 0x3003200)
#define BgmMapNextNum (*(volatile unsigned short*) 0x3003202)
#define BgmMapNowNum (*(volatile unsigned short*) 0x3003202)
#define BgmMapusPlyNum_TrackGroupId (*(volatile unsigned char*) 0x3003206)

#define TrackGroupHeader ((volatile unsigned int*) 0x8097FC8)
#define song_table ((volatile unsigned int*) 0x8098028)

#define Sub_8088678_GamePause ((int (*)()) 0x8088679)
#define Sub_806C130_MapBgmChangeMain ((void (*)()) 0x806C131)
#define Sub_8002D58_MPlayVolumeControl ((void (*)(unsigned int, unsigned short, unsigned short)) 0x8002D59)

// my variables
#define unk_300001F (*(volatile unsigned char*) 0x300001F)

void Sub_80001CC_MainGameLoopCase4Hook()
{
    unsigned short v4;
    if ( Sub_8088678_GamePause() )
    {
        v4 = cPauseFlag;
        if ( cPauseFlag == 2 )
        {
            if ( ucTitle2f )
            {
                GlobalGameMode = 11;
            }
            else
            {
                ucGateNum = ucTitle2f;
                GlobalGameMode = 1;
                sGameSeq = 21;
            }
            return;
        }
        if ( cPauseFlag > 2 )
        {
            if ( cPauseFlag == 3 )
            {
                cPauseFlag = 0;
                GlobalGameMode = v4;
                return;
            }
        }
        else if ( cPauseFlag == 1 )
        {
            GlobalGameMode = 2;

            // custom code to disable the bg3 text render flag by default
            unk_300001F = 0;
            return;
        }
    }
}